name: david_portfolio_app
description: "A new Flutter project."

publish_to: 'none' # Publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.5.1

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0

flutter:

  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - lib/assets/images/

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/to/resolution-aware-images

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/to/asset-from-package

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: Gilroy-Bold-120
      fonts:
        - asset: lib/assets/fonts/Gilroy-Bold-120.otf
          weight: 600
    - family: Gilroy-Bold
      fonts:
        - asset: lib/assets/fonts/Gilroy-Bold.ttf
          weight: 600
  
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/to/font-from-package
